apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: "$DOCKER_IMAGE:$IMAGE_TAG"
        ports:
        - containerPort: 8080
