apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  namespace: default
spec:
  type: NodePort
  selector:
    app: spring-petclinic
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30036 
